// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUpOXFmtQNC_tc6sXSemf1deTaz6npk0M',
    appId: '1:21252990754:web:008b749b1648bd4d1ce77b',
    messagingSenderId: '21252990754',
    projectId: 'insta-d1992',
    authDomain: 'insta-d1992.firebaseapp.com',
    storageBucket: 'insta-d1992.firebasestorage.app',
    measurementId: 'G-7XJ9Y8YDWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBaddS2__eBdvquMecZsQPSIJ14YOI4IY',
    appId: '1:21252990754:android:46e88a09650b2e451ce77b',
    messagingSenderId: '21252990754',
    projectId: 'insta-d1992',
    storageBucket: 'insta-d1992.firebasestorage.app',
  );
}
